export {default as Dashboard} from './Dashboard'
export {default as ManageClients} from './ManageClients'
export {default as ManagePurchases} from './ManagePurchases'
export {default as Products} from './Products'
export {default as NotFound} from './NotFound'
export {default as Layout} from './Layout'